# Generated by Django 4.2.21 on 2025-05-22 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='current_address',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='education',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='education',
            name='major',
        ),
        migrations.RemoveField(
            model_name='professionalinformation',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='professionalinformation',
            name='previous_company_name',
        ),
        migrations.RemoveField(
            model_name='professionalinformation',
            name='previous_job',
        ),
        migrations.RemoveField(
            model_name='professionalinformation',
            name='previous_job_title',
        ),
        migrations.RemoveField(
            model_name='professionalinformation',
            name='reason_for_leaving',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='alternate_phone',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='same_as_permanent',
        ),
    ]
