# Generated by Django 4.2.21 on 2025-05-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_current_address_userdetail_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalinformation',
            name='location',
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='drivers_license',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Prefer not to say')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('SI', 'Single'), ('MA', 'Married')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='national_id_passport',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='tax_id_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
