# Generated by Django 4.2.21 on 2025-05-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_professionalinformation_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='password_hash',
            field=models.CharField(default=1234, max_length=128),
            preserve_default=False,
        ),
    ]
